linters:
  enable:
    - gocyclo
    - revive
    - misspell
    - unused
    
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 16

run:
  skip-dirs:
    - iphlpapi
    - package
    - test
