before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
    # - darwin

archives:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  wrap_in_directory: true
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
    - src: 'vipconfig/*.yml'
      strip_parent: true
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'