before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
    # - darwin

archives:
- name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
    - src: 'vipconfig/*.yml'
      strip_parent: true

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  # note that this is an array of nfpm configs
  -
    file_name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

    vendor: CYBERTEC PostgreSQL International GmbH
    homepage: https://github.com/cybertec-postgresql/vip-manager/
    maintainer: Julian Markwort <julian.markwort@cybertec.at>
    description: Manages a virtual IP based on state kept in etcd/consul
    license: BSD 2-Clause License
    section: default
    
    provides:
      - vip-manager

    formats:
      - deb
      - rpm
    
    contents:
      - src: vipconfig/vip-manager.yml
        dst: /etc/default/vip-manager.yml
        type: config

      - src: vip-manager.service
        dst: /lib/systemd/system/vip-manager.service

      - src: LICENSE
        dst: /usr/share/doc/vip-manager/LICENSE
